/* La frase del día: 365 frases (una por día del año; el 29 de febrero repite la del 28). Orden fijo y mezclado. [texto, autor] */
const FRASES = [
  ["No tiene sentido volver a ayer, porque entonces yo era una persona diferente.", "Lewis Carroll"],
  ["Con paciencia y calma se sube un burro a una palma.", "Refrán español"],
  ["Nadie puede hacerte sentir inferior sin tu consentimiento.", "Eleanor Roosevelt"],
  ["Todo parece imposible hasta que se hace.", "Nelson Mandela"],
  ["Un optimista ve una oportunidad en toda calamidad; un pesimista ve una calamidad en toda oportunidad.", "Winston Churchill"],
  ["Solo sé que no sé nada.", "Sócrates"],
  ["El secreto de una buena vejez no es otra cosa que un pacto honrado con la soledad.", "Gabriel García Márquez"],
  ["En algún lugar, algo increíble está esperando ser descubierto.", "Carl Sagan"],
  ["Conviértete en el que eres.", "Friedrich Nietzsche"],
  ["Si tuviera ocho horas para cortar un árbol, pasaría seis afilando el hacha.", "Abraham Lincoln"],
  ["Si tienes un jardín y una biblioteca, lo tienes todo.", "Cicerón"],
  ["Todos nuestros sueños pueden hacerse realidad si tenemos el coraje de perseguirlos.", "Walt Disney"],
  ["Hacer es la mejor manera de decir.", "José Martí"],
  ["La vida, si sabes usarla, es larga.", "Séneca"],
  ["Sufrimos más en la imaginación que en la realidad.", "Séneca"],
  ["El tiempo que dedicaste a tu rosa es lo que la hace tan importante.", "Antoine de Saint-Exupéry"],
  ["Mañana será otro día.", "Refrán español"],
  ["Nuestras dudas son traidoras y nos hacen perder el bien que podríamos ganar por miedo a intentarlo.", "William Shakespeare"],
  ["Andábamos sin buscarnos, pero sabiendo que andábamos para encontrarnos.", "Julio Cortázar"],
  ["Cultivar el espíritu es tan necesario como el alimento para el cuerpo.", "Cicerón"],
  ["El hombre es la medida de todas las cosas.", "Protágoras"],
  ["Lo bueno, si breve, dos veces bueno.", "Baltasar Gracián"],
  ["Hay que dar tiempo al tiempo.", "Refrán español"],
  ["No hay mal que cien años dure.", "Refrán español"],
  ["No heredamos la tierra de nuestros antepasados: la tomamos prestada de nuestros hijos.", "Proverbio indígena"],
  ["Ser o no ser, esa es la cuestión.", "William Shakespeare"],
  ["No todos podemos hacer grandes cosas, pero sí pequeñas cosas con gran amor.", "Madre Teresa de Calcuta"],
  ["Aun la noche más oscura termina con la salida del sol.", "Victor Hugo"],
  ["Pienso, luego existo.", "René Descartes"],
  ["No hay atajo sin trabajo.", "Proverbio popular"],
  ["Lo que buscas te está buscando.", "Rumi"],
  ["Ninguna cosa grande se crea de repente.", "Epicteto"],
  ["El mundo rompe a todos y después muchos son fuertes en los lugares rotos.", "Ernest Hemingway"],
  ["Si puedes mirar, ve. Si puedes ver, repara.", "José Saramago"],
  ["La vida es una serie de colisiones con el futuro.", "José Ortega y Gasset"],
  ["Lo bueno se hace esperar.", "Refrán español"],
  ["Para que surja lo posible es preciso intentar una y otra vez lo imposible.", "Hermann Hesse"],
  ["Cuando se quiere, se puede.", "Refrán español"],
  ["El secreto de la existencia no consiste solo en vivir, sino en saber para qué se vive.", "Fiódor Dostoievski"],
  ["La mayor victoria es la que se logra sobre uno mismo.", "Platón"],
  ["Un pequeño paso para el hombre, un gran salto para la humanidad.", "Neil Armstrong"],
  ["Quien aprende pero no piensa está perdido.", "Confucio"],
  ["Al hombre se le puede arrebatar todo salvo una cosa: la libertad de elegir su actitud ante las circunstancias.", "Viktor Frankl"],
  ["Un árbol que no se puede abarcar con los brazos nace de un diminuto brote.", "Lao Tsé"],
  ["El genio es un uno por ciento de inspiración y un noventa y nueve por ciento de transpiración.", "Thomas Edison"],
  ["Los hombres se hacen justos haciendo cosas justas.", "Aristóteles"],
  ["Tienes que hacer lo que crees que no puedes hacer.", "Eleanor Roosevelt"],
  ["Por la noche durará el llanto, pero a la mañana vendrá la alegría.", "Salmos"],
  ["La verdad adelgaza y no quiebra, y siempre anda sobre la mentira como el aceite sobre el agua.", "Miguel de Cervantes"],
  ["En lo más profundo del invierno, aprendí por fin que había en mí un verano invencible.", "Albert Camus"],
  ["El secreto para salir adelante es empezar.", "Mark Twain"],
  ["La gratitud no solo es la mayor de las virtudes, sino la madre de todas las demás.", "Cicerón"],
  ["La fuerza no viene de la capacidad física, sino de una voluntad indomable.", "Mahatma Gandhi"],
  ["Nuestra vida comienza a terminar el día en que guardamos silencio sobre las cosas que importan.", "Martin Luther King Jr."],
  ["El arte de vencer se aprende en las derrotas.", "Simón Bolívar"],
  ["El teatro es la poesía que se levanta del libro y se hace humana.", "Federico García Lorca"],
  ["La naturaleza no se apresura y, sin embargo, todo se realiza.", "Lao Tsé"],
  ["Obras son amores, y no buenas razones.", "Refrán español"],
  ["Del dicho al hecho hay mucho trecho.", "Refrán español"],
  ["Quien conquista a otros es fuerte; quien se conquista a sí mismo es poderoso.", "Lao Tsé"],
  ["Todo hombre puede ser, si se lo propone, escultor de su propio cerebro.", "Santiago Ramón y Cajal"],
  ["Nada es más poderoso que una idea a la que le ha llegado su tiempo.", "Victor Hugo"],
  ["Actúa con entusiasmo y serás entusiasta.", "Dale Carnegie"],
  ["La originalidad consiste en volver al origen.", "Antoni Gaudí"],
  ["Haz lo que temes y la muerte del miedo es segura.", "Ralph Waldo Emerson"],
  ["Mucha gente pequeña, en lugares pequeños, haciendo cosas pequeñas, puede cambiar el mundo.", "Eduardo Galeano"],
  ["La simplicidad es la máxima sofisticación.", "Leonardo da Vinci"],
  ["Puedes cortar todas las flores, pero no puedes detener la primavera.", "Pablo Neruda"],
  ["Nunca es tarde si la dicha es buena.", "Refrán español"],
  ["Un día sin sonreír es un día perdido.", "Charles Chaplin"],
  ["De grano en grano llena la gallina el papo.", "Refrán español"],
  ["Donde una puerta se cierra, otra se abre.", "Miguel de Cervantes"],
  ["Solo se ve bien con el corazón.", "Antoine de Saint-Exupéry"],
  ["Quien algo quiere, algo le cuesta.", "Refrán español"],
  ["Muy poco se necesita para hacer una vida feliz; todo está dentro de ti, en tu manera de pensar.", "Marco Aurelio"],
  ["El tiempo es la sustancia de que estoy hecho.", "Jorge Luis Borges"],
  ["No es lo que miras lo que importa, es lo que ves.", "Henry David Thoreau"],
  ["Mejor es el camino que la posada.", "Miguel de Cervantes"],
  ["El que canta, su mal espanta.", "Miguel de Cervantes"],
  ["Todo pasa y todo queda, pero lo nuestro es pasar, pasar haciendo caminos.", "Antonio Machado"],
  ["El corazón tiene razones que la razón no entiende.", "Blaise Pascal"],
  ["Sé paciente con todo lo que no está resuelto en tu corazón.", "Rainer Maria Rilke"],
  ["El único modo de hacer un gran trabajo es amar lo que haces.", "Steve Jobs"],
  ["Como un día bien empleado produce un dulce sueño, así una vida bien usada causa una dulce muerte.", "Leonardo da Vinci"],
  ["Cada uno es hijo de sus obras.", "Miguel de Cervantes"],
  ["Si no te gusta algo, cámbialo. Si no puedes cambiarlo, cambia tu actitud.", "Maya Angelou"],
  ["La fortuna ayuda a los valientes.", "Terencio"],
  ["Despacito y buena letra: el hacer las cosas bien importa más que el hacerlas.", "Antonio Machado"],
  ["La herida es el lugar por donde entra la luz.", "Rumi"],
  ["Quien tiene un porqué para vivir encontrará casi siempre el cómo.", "Friedrich Nietzsche"],
  ["Siete veces mide, una vez corta.", "Proverbio ruso"],
  ["Todo fluye. Nadie se baña dos veces en el mismo río.", "Heráclito"],
  ["Tu tiempo es limitado, así que no lo malgastes viviendo la vida de otro.", "Steve Jobs"],
  ["Lo que no me mata me hace más fuerte.", "Friedrich Nietzsche"],
  ["La experiencia es el nombre que damos a nuestros errores.", "Oscar Wilde"],
  ["Tanto si crees que puedes como si crees que no puedes, tienes razón.", "Henry Ford"],
  ["La libertad, Sancho, es uno de los más preciosos dones que a los hombres dieron los cielos.", "Miguel de Cervantes"],
  ["Si algo no es correcto, no lo hagas; si no es verdad, no lo digas.", "Marco Aurelio"],
  ["Lo más difícil es conocerse a uno mismo; lo más fácil, hablar mal de los demás.", "Tales de Mileto"],
  ["La vida sin amor es como un árbol sin flores ni frutos.", "Khalil Gibran"],
  ["La vida es breve; el arte, largo.", "Hipócrates"],
  ["Lo que se honra en un país se cultiva allí.", "Platón"],
  ["Todos piensan en cambiar el mundo, pero nadie piensa en cambiarse a sí mismo.", "León Tolstói"],
  ["Y sin embargo, se mueve.", "Galileo Galilei"],
  ["El trabajo todo lo vence.", "Virgilio"],
  ["La suerte favorece solo a la mente preparada.", "Louis Pasteur"],
  ["La vida es como montar en bicicleta: para mantener el equilibrio hay que seguir moviéndose.", "Albert Einstein"],
  ["Quien siembra, recoge.", "Refrán español"],
  ["Cae siete veces, levántate ocho.", "Proverbio japonés"],
  ["Hay que imaginarse a Sísifo feliz.", "Albert Camus"],
  ["La mejor manera de encontrarte a ti mismo es perderte en el servicio a los demás.", "Mahatma Gandhi"],
  ["Lo que con mucho trabajo se adquiere, más se ama.", "Aristóteles"],
  ["Hay que tener todavía caos dentro de sí para poder dar a luz una estrella danzante.", "Friedrich Nietzsche"],
  ["Más vale pájaro en mano que ciento volando.", "Refrán español"],
  ["Por el esfuerzo, hasta las estrellas.", "Proverbio latino"],
  ["Año nuevo, vida nueva.", "Refrán español"],
  ["Lo que importa no es cuánto se vive, sino cómo.", "Séneca"],
  ["Sin prisa, pero sin pausa.", "Johann Wolfgang von Goethe"],
  ["En medio del caos también hay oportunidad.", "Sun Tzu"],
  ["Más vale prevenir que curar.", "Refrán español"],
  ["Mil velas pueden encenderse con una sola vela, y la vida de esa vela no se acortará.", "Buda"],
  ["Todo lo que una persona puede imaginar, otras podrán hacerlo realidad.", "Julio Verne"],
  ["Nada es permanente excepto el cambio.", "Heráclito"],
  ["A quien madruga, Dios le ayuda.", "Refrán español"],
  ["La esperanza es lo último que se pierde.", "Refrán español"],
  ["Yo soy yo y mi circunstancia, y si no la salvo a ella no me salvo yo.", "José Ortega y Gasset"],
  ["La esperanza es el sueño del hombre despierto.", "Aristóteles"],
  ["Carpe diem: aprovecha el día.", "Horacio"],
  ["Tres cosas no pueden ocultarse por mucho tiempo: el sol, la luna y la verdad.", "Buda"],
  ["Solos podemos hacer tan poco; juntos podemos hacer mucho.", "Helen Keller"],
  ["Imposible es solo una palabra que usan los hombres débiles para vivir fácilmente en el mundo que se les ha dado.", "Muhammad Ali"],
  ["Un hombre que se atreve a perder una hora de tiempo no ha descubierto el valor de la vida.", "Charles Darwin"],
  ["Cuando veas a un hombre bueno, trata de imitarlo; cuando veas a uno malo, examina tu propio corazón.", "Confucio"],
  ["Si estás atravesando el infierno, sigue adelante.", "Winston Churchill"],
  ["La esperanza es esa cosa con plumas que se posa en el alma.", "Emily Dickinson"],
  ["Algunas personas sienten la lluvia; otras solo se mojan.", "Bob Marley"],
  ["Llegué, vi, vencí.", "Julio César"],
  ["No todos los que vagan están perdidos.", "J. R. R. Tolkien"],
  ["No nos atrevemos a muchas cosas porque son difíciles, pero son difíciles porque no nos atrevemos a hacerlas.", "Séneca"],
  ["A buen hambre no hay pan duro.", "Refrán español"],
  ["El hombre está condenado a ser libre.", "Jean-Paul Sartre"],
  ["El tiempo es oro.", "Refrán español"],
  ["Confía en Dios, pero ata tu camello.", "Proverbio árabe"],
  ["Todo vale la pena si el alma no es pequeña.", "Fernando Pessoa"],
  ["La fe que no duda es una fe muerta.", "Miguel de Unamuno"],
  ["Quien poco piensa, mucho se equivoca.", "Leonardo da Vinci"],
  ["A veces las cosas más pequeñas ocupan el lugar más grande en tu corazón.", "A. A. Milne"],
  ["Tener fe es dar el primer paso aun cuando no se ve toda la escalera.", "Martin Luther King Jr."],
  ["Un hombre puede ser destruido, pero no derrotado.", "Ernest Hemingway"],
  ["Apresúrate despacio.", "Augusto"],
  ["Conocer no es suficiente, debemos aplicar. Querer no es suficiente, debemos hacer.", "Johann Wolfgang von Goethe"],
  ["Mira a las estrellas y no a tus pies.", "Stephen Hawking"],
  ["No preguntes qué puede hacer tu país por ti; pregunta qué puedes hacer tú por tu país.", "John F. Kennedy"],
  ["Mientras hay vida, hay esperanza.", "Cicerón"],
  ["Paciencia y barajar.", "Miguel de Cervantes"],
  ["Vivir mañana es vivir demasiado tarde: vive hoy.", "Marcial"],
  ["El miedo es natural en el prudente, y el saberlo vencer es ser valiente.", "Alonso de Ercilla"],
  ["Hoy es siempre todavía.", "Antonio Machado"],
  ["Lo mejor y más hermoso del mundo no puede verse ni tocarse: debe sentirse con el corazón.", "Helen Keller"],
  ["Lo mejor es enemigo de lo bueno.", "Voltaire"],
  ["Lo único que debemos temer es al propio miedo.", "Franklin D. Roosevelt"],
  ["No hay viento favorable para quien no sabe adónde va.", "Séneca"],
  ["La vida no es la que uno vivió, sino la que uno recuerda y cómo la recuerda para contarla.", "Gabriel García Márquez"],
  ["Aún aprendo.", "Francisco de Goya"],
  ["La felicidad de tu vida depende de la calidad de tus pensamientos.", "Marco Aurelio"],
  ["Primero dite a ti mismo lo que quieres ser; y luego haz lo que tengas que hacer.", "Epicteto"],
  ["Lo importante rara vez es urgente, y lo urgente rara vez es importante.", "Dwight D. Eisenhower"],
  ["El comienzo es la parte más importante del trabajo.", "Platón"],
  ["Camarón que se duerme, se lo lleva la corriente.", "Refrán español"],
  ["Somos lo que hacemos para cambiar lo que somos.", "Eduardo Galeano"],
  ["Cada nube tiene un borde de plata.", "Proverbio inglés"],
  ["Quien tiene un amigo, tiene un tesoro.", "Refrán español"],
  ["El tiempo vuela.", "Virgilio"],
  ["Ser culto es el único modo de ser libre.", "José Martí"],
  ["Poco a poco se va lejos.", "Refrán español"],
  ["Quien mucho abarca, poco aprieta.", "Refrán español"],
  ["Nada te turbe, nada te espante; todo se pasa. La paciencia todo lo alcanza.", "Santa Teresa de Jesús"],
  ["Nadie es libre si no es dueño de sí mismo.", "Epicteto"],
  ["Sé agua, amigo mío.", "Bruce Lee"],
  ["Nada es suficiente para quien lo suficiente es poco.", "Epicuro"],
  ["Las grandes cosas se hacen con una serie de pequeñas cosas juntas.", "Vincent van Gogh"],
  ["Lo importante es no dejar de hacerse preguntas.", "Albert Einstein"],
  ["En medio de la dificultad reside la oportunidad.", "Albert Einstein"],
  ["La pluma es la lengua del alma.", "Miguel de Cervantes"],
  ["La esperanza es un buen desayuno, pero una mala cena.", "Francis Bacon"],
  ["Si no puedes volar, corre; si no puedes correr, camina; si no puedes caminar, arrástrate; pero sigue adelante.", "Martin Luther King Jr."],
  ["Vivir es lo más raro del mundo: la mayoría de la gente existe, nada más.", "Oscar Wilde"],
  ["Quien no sabe lo que ocurrió antes de su nacimiento será siempre un niño.", "Cicerón"],
  ["La mente no es un vaso que hay que llenar, sino un fuego que hay que encender.", "Plutarco"],
  ["Lo que no puedo crear, no lo entiendo.", "Richard Feynman"],
  ["Si piensas que eres demasiado pequeño para hacer una diferencia, intenta dormir con un mosquito en la habitación.", "Dalái Lama"],
  ["He fallado más de nueve mil tiros en mi carrera. He perdido casi trescientos partidos. Por eso tengo éxito.", "Michael Jordan"],
  ["Atrévete a saber.", "Horacio"],
  ["La inversión en conocimiento paga el mejor interés.", "Benjamin Franklin"],
  ["Todo lo que te viniere a la mano para hacer, hazlo según tus fuerzas.", "Eclesiastés"],
  ["Es suficiente tener buen ingenio; lo principal es aplicarlo bien.", "René Descartes"],
  ["Lo que embellece al desierto es que en alguna parte esconde un pozo.", "Antoine de Saint-Exupéry"],
  ["Más vale solo que mal acompañado.", "Refrán español"],
  ["El que persevera, alcanza.", "Refrán español"],
  ["Fracasar es simplemente la oportunidad de empezar de nuevo, esta vez con más inteligencia.", "Henry Ford"],
  ["Caminante, no hay camino, se hace camino al andar.", "Antonio Machado"],
  ["Hay cosas que dependen de nosotros y cosas que no dependen de nosotros.", "Epicteto"],
  ["Lo que no se empieza hoy, nunca se acaba mañana.", "Johann Wolfgang von Goethe"],
  ["Que otros se jacten de las páginas que han escrito; a mí me enorgullecen las que he leído.", "Jorge Luis Borges"],
  ["Sábete, Sancho, que no es un hombre más que otro si no hace más que otro.", "Miguel de Cervantes"],
  ["Lo esencial es invisible a los ojos.", "Antoine de Saint-Exupéry"],
  ["La forma de comenzar es dejar de hablar y empezar a hacer.", "Walt Disney"],
  ["A buen entendedor, pocas palabras bastan.", "Refrán español"],
  ["Roma no se construyó en un día.", "Refrán español"],
  ["Juventud, divino tesoro.", "Rubén Darío"],
  ["Mientras dura la vida, aprende a vivir.", "Séneca"],
  ["El que no arriesga, no gana.", "Refrán español"],
  ["El carácter es el destino.", "Heráclito"],
  ["Sigue tu camino y deja que la gente hable.", "Dante Alighieri"],
  ["El valor es el comienzo de la acción; la fortuna, su desenlace.", "Demócrito"],
  ["Visión sin acción es un sueño; acción sin visión es una pesadilla.", "Proverbio japonés"],
  ["Nunca cedáis, nunca, nunca, nunca.", "Winston Churchill"],
  ["El principio es la mitad del todo.", "Aristóteles"],
  ["El mejor momento para plantar un árbol fue hace veinte años. El segundo mejor momento es ahora.", "Proverbio chino"],
  ["La salud no lo es todo, pero sin ella todo lo demás es nada.", "Arthur Schopenhauer"],
  ["Es inútil la palabra del filósofo si no cura algún sufrimiento humano.", "Epicuro"],
  ["La suerte está echada.", "Julio César"],
  ["Conócete a ti mismo.", "Inscripción del templo de Apolo, en Delfos"],
  ["La naturaleza no hace nada en vano.", "Aristóteles"],
  ["La sabiduría comienza en la capacidad de asombro.", "Sócrates"],
  ["Cada día trae su afán.", "Refrán español"],
  ["La fortuna ayuda a los audaces.", "Virgilio"],
  ["Intenta no volverte un hombre de éxito, sino volverte un hombre de valor.", "Albert Einstein"],
  ["Aquellos que no creen en la magia nunca la encontrarán.", "Roald Dahl"],
  ["Qué maravilloso es que nadie necesite esperar ni un solo momento antes de empezar a mejorar el mundo.", "Ana Frank"],
  ["Un viaje de mil millas comienza con un solo paso.", "Lao Tsé"],
  ["La educación tiene raíces amargas, pero sus frutos son dulces.", "Aristóteles"],
  ["No te rindas, aún estás a tiempo de alcanzar y comenzar de nuevo.", "Mario Benedetti"],
  ["Saber es poder.", "Francis Bacon"],
  ["No hay mal que por bien no venga.", "Refrán español"],
  ["El que lee mucho y anda mucho, ve mucho y sabe mucho.", "Miguel de Cervantes"],
  ["Mantente hambriento, mantente alocado.", "Steve Jobs"],
  ["Quien anda con sabios, sabio será.", "Proverbios"],
  ["Lo que hemos de aprender a hacer, lo aprendemos haciendo.", "Aristóteles"],
  ["La mejor venganza es no ser como tu enemigo.", "Marco Aurelio"],
  ["Nuestra mayor gloria no está en no caer nunca, sino en levantarnos cada vez que caemos.", "Oliver Goldsmith"],
  ["Si he visto más lejos, es porque estaba subido a hombros de gigantes.", "Isaac Newton"],
  ["Lo más difícil es la decisión de actuar; el resto es mera tenacidad.", "Amelia Earhart"],
  ["El sabio se basta a sí mismo.", "Séneca"],
  ["Hay que perseverar y, sobre todo, tener confianza en uno mismo.", "Marie Curie"],
  ["Ve confiadamente en la dirección de tus sueños. Vive la vida que has imaginado.", "Henry David Thoreau"],
  ["Cultivemos nuestro jardín.", "Voltaire"],
  ["Todo el mundo es un escenario, y todos los hombres y mujeres, meros actores.", "William Shakespeare"],
  ["Todo lo que tenemos que decidir es qué hacer con el tiempo que se nos ha dado.", "J. R. R. Tolkien"],
  ["El valiente no es quien no siente miedo, sino quien conquista ese miedo.", "Nelson Mandela"],
  ["Nuestra recompensa se encuentra en el esfuerzo y no en el resultado. Un esfuerzo total es una victoria completa.", "Mahatma Gandhi"],
  ["El hierro se oxida por falta de uso; así también la inactividad consume el intelecto.", "Leonardo da Vinci"],
  ["Son nuestras elecciones, mucho más que nuestras habilidades, las que muestran lo que somos.", "J. K. Rowling"],
  ["Pies, ¿para qué los quiero si tengo alas para volar?", "Frida Kahlo"],
  ["¿Qué es lo más importante del mundo? Las personas, las personas, las personas.", "Proverbio maorí"],
  ["El tiempo es vida, y la vida reside en el corazón.", "Michael Ende"],
  ["Mucho mejor es atreverse a grandes cosas, aunque se alternen con fracasos, que formar fila con esos pobres espíritus que ni disfrutan mucho ni sufren mucho.", "Theodore Roosevelt"],
  ["La confianza en uno mismo es el primer secreto del éxito.", "Ralph Waldo Emerson"],
  ["No son las cosas las que nos perturban, sino la opinión que tenemos de ellas.", "Epicteto"],
  ["Más vale tarde que nunca.", "Refrán español"],
  ["Una golondrina no hace verano.", "Refrán español"],
  ["Querer es poder.", "Refrán español"],
  ["Dime con quién andas y te diré quién eres.", "Refrán español"],
  ["La vida solo puede ser comprendida mirando hacia atrás, pero debe ser vivida mirando hacia delante.", "Søren Kierkegaard"],
  ["Entre los individuos, como entre las naciones, el respeto al derecho ajeno es la paz.", "Benito Juárez"],
  ["No soy un santo, a menos que consideres santo a un pecador que sigue intentándolo.", "Nelson Mandela"],
  ["Quien siembra vientos recoge tempestades.", "Refrán español"],
  ["Nunca digas de esta agua no beberé.", "Refrán español"],
  ["¿Qué es la vida? Un frenesí. ¿Qué es la vida? Una ilusión, una sombra, una ficción; que toda la vida es sueño, y los sueños, sueños son.", "Pedro Calderón de la Barca"],
  ["Al amanecer, cuando te cueste levantarte, piensa: me despierto para hacer el trabajo de un ser humano.", "Marco Aurelio"],
  ["Somos lo que hacemos repetidamente. La excelencia, entonces, no es un acto, sino un hábito.", "Will Durant"],
  ["Sin música la vida sería un error.", "Friedrich Nietzsche"],
  ["El éxito suele llegar a quienes están demasiado ocupados para ir en su busca.", "Henry David Thoreau"],
  ["La imaginación es más importante que el conocimiento.", "Albert Einstein"],
  ["No dejes para mañana lo que puedas hacer hoy.", "Refrán español"],
  ["Inteligencia, dame el nombre exacto de las cosas.", "Juan Ramón Jiménez"],
  ["El cambio es ley de vida.", "John F. Kennedy"],
  ["Quien tiene boca se equivoca.", "Refrán español"],
  ["Mejorar es cambiar; ser perfecto es haber cambiado con frecuencia.", "Winston Churchill"],
  ["Quien tiene paciencia obtiene lo que desea.", "Benjamin Franklin"],
  ["Quien mira hacia fuera sueña; quien mira hacia dentro despierta.", "Carl Gustav Jung"],
  ["La diligencia es madre de la buena ventura.", "Miguel de Cervantes"],
  ["La victoria pertenece al más perseverante.", "Napoleón Bonaparte"],
  ["Después de la tormenta llega la calma.", "Refrán español"],
  ["Ningún acto de bondad, por pequeño que sea, es en vano.", "Esopo"],
  ["No he fracasado. Solo he encontrado diez mil formas que no funcionan.", "Thomas Edison"],
  ["Todo esfuerzo tiene su recompensa.", "Refrán español"],
  ["Haz bien y no mires a quién.", "Refrán español"],
  ["No se ganó Zamora en una hora.", "Refrán español"],
  ["Que el camino salga a tu encuentro.", "Bendición irlandesa"],
  ["Un ganador es un soñador que nunca se rinde.", "Nelson Mandela"],
  ["La respuesta amable calma la ira.", "Proverbios"],
  ["La amistad es un alma que habita en dos cuerpos.", "Aristóteles"],
  ["Los cobardes mueren muchas veces antes de su muerte.", "William Shakespeare"],
  ["Aunque el mundo está lleno de sufrimiento, también está lleno de superación.", "Helen Keller"],
  ["¿Me contradigo? Muy bien, me contradigo. Soy amplio, contengo multitudes.", "Walt Whitman"],
  ["El odio no puede expulsar al odio: solo el amor puede hacerlo.", "Martin Luther King Jr."],
  ["Todo tiene su tiempo, y todo lo que se quiere debajo del cielo tiene su hora.", "Eclesiastés"],
  ["La edad es cuestión de mentalidad sobre la materia: si no te importa, no importa.", "Mark Twain"],
  ["Lo que bien empieza, bien acaba.", "Refrán español"],
  ["Si no sabes adónde vas, cualquier camino te llevará allí.", "Lewis Carroll"],
  ["Siempre perdona a tus enemigos: nada los molesta tanto.", "Oscar Wilde"],
  ["El hombre nace libre, y en todas partes está encadenado.", "Jean-Jacques Rousseau"],
  ["El corazón alegre es buena medicina.", "Proverbios"],
  ["Cuando ya no somos capaces de cambiar una situación, nos enfrentamos al desafío de cambiarnos a nosotros mismos.", "Viktor Frankl"],
  ["No dejes que lo que no puedes hacer interfiera con lo que sí puedes hacer.", "John Wooden"],
  ["Lo prometido es deuda.", "Refrán español"],
  ["Ningún camino es largo con buena compañía.", "Proverbio turco"],
  ["No puedes cruzar el mar simplemente mirando el agua.", "Rabindranath Tagore"],
  ["A quien a buen árbol se arrima, buena sombra le cobija.", "Refrán español"],
  ["El amor es tan corto y es tan largo el olvido.", "Pablo Neruda"],
  ["La moda pasa, el estilo permanece.", "Coco Chanel"],
  ["Cuando una puerta se cierra, otra se abre; pero a menudo miramos tanto tiempo la puerta cerrada que no vemos la que se ha abierto.", "Alexander Graham Bell"],
  ["Aprender sin pensar es inútil; pensar sin aprender, peligroso.", "Confucio"],
  ["Si quieres ir rápido, camina solo; si quieres llegar lejos, ve acompañado.", "Proverbio africano"],
  ["El movimiento se demuestra andando.", "Refrán español"],
  ["Hice lo mejor que pude con lo que sabía, y cuando supe más, lo hice mejor.", "Maya Angelou"],
  ["La vida es una aventura atrevida o no es nada.", "Helen Keller"],
  ["Tienes poder sobre tu mente, no sobre los acontecimientos externos. Date cuenta de esto y encontrarás la fuerza.", "Marco Aurelio"],
  ["Mi vida ha estado llena de terribles desgracias, la mayoría de las cuales nunca sucedieron.", "Michel de Montaigne"],
  ["Dos caminos se bifurcaban en un bosque, y yo tomé el menos transitado: eso ha marcado toda la diferencia.", "Robert Frost"],
  ["Más vale un «toma» que dos «te daré».", "Miguel de Cervantes"],
  ["La práctica hace al maestro.", "Refrán español"],
  ["Elige el mejor modo de vida, y la costumbre lo hará agradable.", "Pitágoras"],
  ["Cada día es el mejor día del año.", "Ralph Waldo Emerson"],
  ["Dadme un punto de apoyo y moveré el mundo.", "Arquímedes"],
  ["Los libros son espejos: solo se ve en ellos lo que uno ya lleva dentro.", "Carlos Ruiz Zafón"],
  ["No importa lo despacio que vayas, siempre y cuando no te detengas.", "Confucio"],
  ["La felicidad es cuando lo que piensas, lo que dices y lo que haces están en armonía.", "Mahatma Gandhi"],
  ["La gota excava la piedra no por su fuerza, sino por su constancia.", "Ovidio"],
  ["A partir de cierto punto no hay retorno. Ese es el punto que hay que alcanzar.", "Franz Kafka"],
  ["Todo lo negativo —presión, desafíos— es una oportunidad para elevarme.", "Kobe Bryant"],
  ["Un niño, un profesor, un libro y un lápiz pueden cambiar el mundo.", "Malala Yousafzai"],
  ["La educación es el arma más poderosa que puedes usar para cambiar el mundo.", "Nelson Mandela"],
  ["La oscuridad no puede expulsar a la oscuridad: solo la luz puede hacerlo.", "Martin Luther King Jr."],
  ["El tiempo es el mayor innovador.", "Francis Bacon"],
  ["La vida es aquello que te va sucediendo mientras te empeñas en hacer otros planes.", "John Lennon"],
  ["No tengo talentos especiales, solo soy profundamente curioso.", "Albert Einstein"],
  ["La mayoría de la gente es tan feliz como decide serlo.", "Abraham Lincoln"],
  ["Si quieres que algo se haga, encárgaselo a una persona ocupada.", "Benjamin Franklin"],
  ["No es que tengamos poco tiempo, sino que perdemos mucho.", "Séneca"],
  ["Al mal tiempo, buena cara.", "Refrán español"],
  ["Quien conoce a los demás es sabio; quien se conoce a sí mismo es sabio de verdad.", "Lao Tsé"],
  ["Nada grande se ha logrado sin entusiasmo.", "Ralph Waldo Emerson"],
  ["No hay camino hacia la felicidad: la felicidad es el camino.", "Thich Nhat Hanh"],
  ["Errar es humano.", "Cicerón"],
  ["Pobre no es quien tiene poco, sino quien mucho desea.", "Séneca"],
  ["Una vida sin examen no merece ser vivida.", "Sócrates"],
  ["Lo que haces marca la diferencia, y tienes que decidir qué tipo de diferencia quieres marcar.", "Jane Goodall"],
  ["El que la sigue, la consigue.", "Refrán español"],
  ["La felicidad no es algo hecho: viene de tus propias acciones.", "Dalái Lama"],
  ["Cada cosa a su tiempo.", "Refrán español"],
  ["Yo no estudio para saber más, sino para ignorar menos.", "Sor Juana Inés de la Cruz"],
  ["No puedes volver atrás y cambiar el principio, pero puedes empezar donde estás y cambiar el final.", "C. S. Lewis"],
  ["Quien mueve una montaña empieza apartando piedras pequeñas.", "Proverbio chino"],
  ["Cuando quieres algo, todo el universo conspira para que puedas realizarlo.", "Paulo Coelho"],
  ["La riqueza no consiste en tener grandes posesiones, sino en tener pocas necesidades.", "Epicteto"],
  ["Quien va despacio, va sano y llega lejos.", "Proverbio italiano"],
  ["Nada en la vida debe ser temido, solamente comprendido. Ahora es el momento de comprender más para temer menos.", "Marie Curie"],
  ["Quien sabe contentarse siempre tiene suficiente.", "Lao Tsé"],
  ["El que no sabe gozar de la ventura cuando le viene, no debe quejarse si se pasa.", "Miguel de Cervantes"],
  ["No hay rosas sin espinas.", "Refrán español"],
  ["La unión hace la fuerza.", "Refrán español"],
  ["Haz lo que puedas, con lo que tengas, donde estés.", "Theodore Roosevelt"],
  ["Si lloras porque se ha puesto el sol, las lágrimas no te dejarán ver las estrellas.", "Rabindranath Tagore"],
];
