/* La frase del día: 365 frases motivadoras (una por día del año; el 29 de febrero repite la primera). Orden fijo y mezclado. */
const FRASES = [
  "Ve a tu ritmo; lo importante es que sigas en el camino.",
  "No dejes que el cansancio te robe la ilusión: descansa y sigue.",
  "No hace falta hacerlo todo hoy; hace falta hacer lo importante.",
  "Tu agenda puede ser ligera y tu día, bonito.",
  "Paso a paso, el camino se hace camino.",
  "No eres lo que te ha salido mal, eres lo que haces a partir de ello.",
  "Eres más que tus dudas, más que tus miedos y más que tus errores.",
  "Aprende, ajusta y vuelve a intentarlo: así se crece.",
  "La vida se disfruta más cuando se vive con intención.",
  "Escribe lo que quieres lograr y dale un primer paso hoy.",
  "Un buen café, un buen plan y una buena actitud: el día está ganado.",
  "No te rindas justo cuando está empezando a funcionar.",
  "Cada pequeño avance de hoy es un gran paso para tu yo de mañana.",
  "Haz una cosa a la vez y hazla con ganas.",
  "Lo que hoy practicas mañana será natural.",
  "Cuando todo parezca difícil, simplifica: haz solo lo siguiente.",
  "Mereces el esfuerzo que estás haciendo por ti.",
  "No tienes que cargarlo todo tú solo: pedir ayuda también es valentía.",
  "Cuando dudes, da un paso pequeño: la duda se achica cuando te mueves.",
  "Un día a la vez es suficiente para llegar muy lejos.",
  "Estás exactamente en el punto de partida de algo bonito.",
  "Un día más es una oportunidad más: aprovéchala.",
  "Con cada decisión sensata, te acercas a la vida que quieres.",
  "Mereces pausas tanto como metas.",
  "Leer unas páginas hoy es regalarte un mundo nuevo.",
  "Esta semana puede ser tu mejor semana: empieza con buen pie.",
  "Empieza ahora, con lo que tienes; el resto irá apareciendo por el camino.",
  "La disciplina de hoy es la libertad de mañana.",
  "Respira, sonríe y sigue: ya queda menos.",
  "Cada pasito suma; no los desprecies.",
  "Una lista corta y cumplida vale más que una larga ignorada.",
  "Empieza donde estás, usa lo que tienes, haz lo que puedas.",
  "Un rato de calma hoy te regala claridad mañana.",
  "Sigue adelante, incluso cuando vayas despacio: avanzar es avanzar.",
  "Sonríe: ya has llegado hasta aquí, y eso no es poco.",
  "El primer paso es el más difícil; el segundo ya es costumbre.",
  "Si hoy no puedes más, hoy te toca descansar; mañana volverás a poder.",
  "Cambiar de plan no es fracasar, es adaptarse.",
  "Quien se organiza hoy duerme tranquilo esta noche.",
  "Pon tu mirada en la meta y tus manos en el trabajo de hoy.",
  "Lo que te da miedo hoy será tu orgullo mañana.",
  "Tú decides con qué actitud empiezas el día; empieza con buena.",
  "El mejor momento para empezar fue ayer; el segundo mejor es ahora.",
  "Los buenos hábitos se construyen un día a la vez; hoy te toca uno.",
  "Hay una fuerza tranquila en ti que sabe cómo seguir.",
  "No cuentes los días, haz que los días cuenten.",
  "Hoy puedes ser un poco más valiente que ayer.",
  "Cada día sabes un poco más que ayer: eso es crecer.",
  "Haz tu parte con ganas y deja que el tiempo haga la suya.",
  "No hay prisa por llegar, pero sí alegría por empezar.",
  "Haz lo que puedas y confía: el resto se irá acomodando.",
  "Hay una versión de ti que ya lo logró: ve a su encuentro.",
  "Lo mejor de ti aparece cuando no te rindes.",
  "Cada día que insistes, te haces más fuerte.",
  "Hoy puedes elegir cómo afrontar el día, y eso ya es un poder enorme.",
  "Las personas constantes no son más fuertes: simplemente no paran.",
  "Tu constancia vale más que tu talento.",
  "Hoy es el momento perfecto para hacer eso que llevas tiempo posponiendo.",
  "Si lo apuntas, lo cumples: tu agenda es tu mejor aliada.",
  "El miedo se hace pequeño cuando empiezas a moverte.",
  "Un gran día empieza con un pequeño sí a ti mismo.",
  "Ten un plan, pero déjale un hueco a lo inesperado y bonito.",
  "Confía en tu criterio: llegaste hasta aquí por algo.",
  "Agradece a quien te ayudó: es una forma preciosa de empezar el día.",
  "Siempre hay un nuevo comienzo esperando dentro de cada final.",
  "Un buen plan, un poco de ganas y un primer paso: ya tienes lo necesario.",
  "Cinco minutos de acción valen más que una hora de dudas.",
  "No dejes que el miedo a equivocarte te impida intentarlo.",
  "Dedícale a tus sueños el mismo esfuerzo que a tus obligaciones.",
  "No esperes a sentirte listo: empieza y la confianza llegará después.",
  "Una gota insiste hasta que la piedra cede: tú también puedes.",
  "Una buena rutina es un abrazo que te das cada día.",
  "Las pequeñas victorias de hoy forman la gran victoria de mañana.",
  "Haz que cada día cuente con una acción que te acerque a lo que quieres.",
  "Cada paso hacia delante, por pequeño que sea, ya es avanzar.",
  "Respira tres veces y vuelve a empezar: siempre se puede.",
  "La ilusión es el combustible de los grandes proyectos.",
  "Lo bonito de hoy puede estar en un detalle pequeño; mira con atención.",
  "Pide eso que quieres; el no ya lo tienes.",
  "Tu energía va donde tú la diriges; dirígela a lo que importa.",
  "Cada día que sigues adelante es una victoria silenciosa.",
  "Cada tarea que terminas es una victoria, aunque nadie la aplauda.",
  "Sonríe al espejo: ahí está la persona que va a lograrlo.",
  "Hoy es un día estupendo para empezar algo nuevo.",
  "Elige avanzar, aunque sea un poco; el movimiento ya es un triunfo.",
  "Haz hoy aquello que tu corazón lleva tiempo pidiéndote.",
  "Tu zona de confort es bonita, pero lo mejor está un poco más allá.",
  "Cada mañana es una página en blanco: escribe algo de lo que te alegres.",
  "Hoy es un día más para demostrarte lo que puedes.",
  "Tu actitud puede convertir un día normal en un gran día.",
  "Tú pones el ritmo de tu día; elige uno que te guste.",
  "Tu sonrisa de hoy es el mejor comienzo para cualquier plan.",
  "Cada día que cuidas de tus metas, ellas cuidan de ti.",
  "Tu cerebro es un músculo: cuanto más lo usas, más fuerte se vuelve.",
  "Un pequeño cambio hoy puede cambiar tu año entero.",
  "Sigue tu intuición y apóyate en tu esfuerzo.",
  "Siembra buenos pensamientos y verás florecer buenos días.",
  "Cada hora cuenta: úsala en lo que te hace feliz.",
  "Un poco más de perseverancia y lo difícil se vuelve posible.",
  "Tu esfuerzo tiene sentido aunque aún no veas el resultado.",
  "Los obstáculos son parte del camino, no el final.",
  "Lo que te propongas con ilusión se vuelve más ligero.",
  "Anímate: hoy tienes más posibilidades que ayer.",
  "Lo que hoy es un problema mañana será una anécdota.",
  "Que tus ganas sean más grandes que tus excusas.",
  "Cada gran logro empezó como una idea que alguien se atrevió a probar.",
  "No te pares a pensar en cuánto falta: mira cuánto has avanzado ya.",
  "Lo que haces cada día importa más que lo que haces de vez en cuando.",
  "Atrévete a empezar, aunque aún no tengas todas las respuestas.",
  "Sé el motivo de una sonrisa de alguien hoy.",
  "No hace falta saberlo todo para empezar: se aprende caminando.",
  "Con ilusión, todo pesa menos.",
  "Termina el día pensando en una cosa buena que hiciste hoy.",
  "Quien se atreve a empezar ya está más cerca que quien solo lo piensa.",
  "Lo que has aprendido hasta hoy ya te hace más sabio que ayer.",
  "Hoy, deja que la ilusión lleve la voz cantante.",
  "Las personas que te quieren creen en ti; hoy empieza tú también.",
  "Hoy no hace falta ser productivo, basta con ser constante.",
  "Equivocarse es parte de aprender: no hay aprendizaje sin ensayo.",
  "Cada día tienes la posibilidad de empezar otra vez, y eso es un regalo.",
  "Las mejores historias tienen un momento en que parecía imposible.",
  "Las cosas buenas llegan a quien se mueve hacia ellas.",
  "Agradece lo que tienes mientras trabajas por lo que quieres.",
  "Tu tiempo es tuyo: reparte bien lo que más te importa.",
  "Cada pequeño esfuerzo es una semilla de algo grande.",
  "Hoy puedes ser la razón por la que alguien crea en sí mismo.",
  "Detente un momento y celebra todo lo que ya has conseguido.",
  "Los días buenos se hacen, no solo se esperan.",
  "Un objetivo a la vez: así se llega a todos.",
  "Aprender algo nuevo cada día es la mejor manera de crecer.",
  "Lo primero que haces por la mañana marca el tono del resto del día.",
  "Hoy toca ser constante, amable y valiente.",
  "Planifica con cariño, ejecuta con calma y descansa con ganas.",
  "Quien aprende nunca envejece del todo.",
  "Hoy puedes cerrar un asunto pendiente y sentirte más ligero.",
  "Haz de tu agenda un espacio para lo que importa: tú, los tuyos y tus sueños.",
  "La perseverancia es el camino silencioso del éxito.",
  "Tu vida es el proyecto más importante: cuídalo con cariño.",
  "Respira hondo: lo estás haciendo mejor de lo que piensas.",
  "Cada final es el comienzo de otra cosa; ábrete a ella.",
  "Lo estás haciendo bien: sigue así.",
  "Una meta clara convierte el esfuerzo en ilusión.",
  "Hoy te toca cuidar de lo que más te importa.",
  "La mejor manera de predecir tu futuro es empezar a construirlo hoy.",
  "Empieza el día con una sonrisa y pregúntate qué bueno puede pasar hoy.",
  "Empieza por lo más pequeño; lo pequeño también mueve montañas.",
  "Lo que hoy parece un esfuerzo, mañana será tu fortaleza.",
  "Prioriza lo que te acerca a tus metas y deja lo demás para después.",
  "Tu perseverancia de hoy es tu logro de mañana.",
  "Nadie nació sabiendo: todos empezaron sin saber.",
  "Hoy, un poco de valentía puede cambiar mucho.",
  "Que hoy tus acciones se parezcan a tus sueños.",
  "Con cada decisión, vas dibujando el día que quieres vivir.",
  "Ten fe en tus capacidades: ya las has demostrado antes.",
  "La confianza se construye cumpliendo pequeñas promesas contigo.",
  "Lo mejor está por venir, y tú ya vas de camino.",
  "Hoy es un gran día para ser mejor que ayer, solo un poquito.",
  "Date permiso para parar un momento; el camino seguirá ahí.",
  "Pon en tu agenda algo que te haga ilusión: tú también cuentas.",
  "Hoy el mundo sonríe a quien le sonríe.",
  "Aquello a lo que dedicas tu tiempo se vuelve parte de tu vida: elígelo bien.",
  "Pasa lo que pase hoy, tú sabrás cómo seguir.",
  "Aprovecha esta mañana: viene con energía nueva para ti.",
  "Cuando sientas que no puedes más, recuerda cuánto has superado ya.",
  "Lo que hoy te cuesta es lo que mañana te hará sentir orgulloso.",
  "Empieza la semana con ganas y termínala con orgullo.",
  "La calma es una fuerza silenciosa que te lleva muy lejos.",
  "Lo importante es la dirección, no la velocidad.",
  "Si tu meta es grande, tu paciencia debe serlo también.",
  "Haz de hoy un día del que tu yo de mañana se sienta orgulloso.",
  "Que tu constancia hable más fuerte que tus dudas.",
  "Hoy es un buen día para dar un paso más hacia lo que quieres.",
  "Hoy brilla un poquito más que ayer: ese es el objetivo.",
  "El éxito es la suma de pequeños esfuerzos repetidos cada día.",
  "Mereces días tranquilos, metas claras y mucha ilusión.",
  "Dormir bien, comer bien y sonreír: la mejor estrategia para cualquier día.",
  "Los grandes logros empiezan con una decisión sencilla: intentarlo.",
  "La mejor forma de tener un buen día es empezar con buen ánimo.",
  "Tu valor no depende de lo que logres hoy.",
  "Celebra lo pequeño: también cuenta y también suma.",
  "Confía en el proceso: las cosas buenas se construyen poco a poco.",
  "Eres capaz de más de lo que has intentado: inténtalo.",
  "Nadie va a vivir tu vida por ti: hazla bonita.",
  "Hay cosas que solo se consiguen con tiempo: dáselo.",
  "Una buena pregunta vale más que una respuesta rápida.",
  "Con un poco de orden y un mucho de ilusión, todo se puede.",
  "Nada cambia si tú no cambias algo: empieza por algo pequeño.",
  "Respira, confía y da el siguiente paso.",
  "No esperes a que se despeje el cielo para empezar a caminar.",
  "Sé paciente con el resultado y constante con el esfuerzo.",
  "Te mereces lo bueno que estás construyendo.",
  "Sigue plantando, aunque aún no veas el árbol.",
  "Que hoy te toque sentirte orgulloso de algo, por pequeño que sea.",
  "Atrévete a probar: lo peor que puede pasar es que aprendas algo.",
  "Un error no es el final: es una lección con prisa.",
  "Mira atrás para tomar impulso, no para quedarte.",
  "Que el día de hoy te sorprenda para bien.",
  "Tu día puede ser sencillo y, aun así, maravilloso.",
  "Cada día es una nueva oportunidad para sorprenderte a ti mismo.",
  "Aprende de ayer, vive el hoy y mira con ilusión al mañana.",
  "Todo gran cambio empieza con una pequeña decisión diaria.",
  "Date un día para empezar; lo demás se encadena solo.",
  "Hazte un favor: empieza por esa tarea que tanto pesa.",
  "Un sueño con plan se llama meta; ponle fecha hoy.",
  "Tu curiosidad es tu mejor herramienta: úsala hoy.",
  "Hoy cuida de lo que sientes; lo que sientes también importa.",
  "Insistir con cariño es más poderoso que correr con prisas.",
  "Habla contigo con el mismo cariño con el que hablas a tus amigos.",
  "Elige bien en qué gastas tu energía: es un tesoro.",
  "No tienes que hacerlo perfecto; tienes que empezar.",
  "Divide lo grande en trozos pequeños y verás que se puede.",
  "Resuelve lo importante primero y el día se vuelve más ligero.",
  "Sé constante con tus metas y flexible con tus caminos.",
  "Lo que hoy es un sueño puede ser tu rutina de mañana.",
  "Prepárate un día bonito: tú puedes hacerlo.",
  "Fíjate en lo lejos que has llegado, no solo en lo que falta.",
  "Eres más capaz de lo que crees y más fuerte de lo que imaginas.",
  "Cada amanecer es una invitación a intentarlo otra vez.",
  "Que la ilusión te acompañe desde la primera hora.",
  "Vive el día con gratitud y lo vivirás doble.",
  "Hoy comprométete con una cosa pequeña y cúmplela.",
  "Si el camino es difícil, probablemente vas hacia algo que merece la pena.",
  "Tu esfuerzo de hoy planta lo que cosecharás mañana.",
  "Hoy, sé amable contigo: también estás haciendo lo que puedes.",
  "No dejes para luego lo que hoy puede ser un buen comienzo.",
  "La gratitud convierte lo normal en extraordinario: fíjate en lo bueno de hoy.",
  "Un paso atrás para tomar impulso sigue siendo parte del avance.",
  "Tu cuerpo y tu mente trabajan contigo: trátalos con gratitud.",
  "Rodéate de quien te impulsa y alégrate por sus logros.",
  "Tu mejor momento es ahora: aprovéchalo con calma y con ganas.",
  "Un rato de esfuerzo hoy vale más que mil intenciones.",
  "Cada vez que te animas, tu confianza crece.",
  "Nada de lo que hagas con cariño se pierde.",
  "Un mensaje de ánimo a alguien querido también te anima a ti.",
  "Terminar lo que empezaste te devuelve la ilusión de seguir.",
  "Saca lo mejor de este día y deja que él saque lo mejor de ti.",
  "Hoy puedes elegir una cosa que te haga bien: elige.",
  "Un día bien planificado es un día con espacio para disfrutar.",
  "Sigue, aunque nadie lo vea: tu esfuerzo no pasa desapercibido.",
  "Una mirada amable cambia el día, empezando por el tuyo.",
  "Los sueños se hacen realidad con trabajo, paciencia y fe en uno mismo.",
  "La motivación te pone en marcha; el hábito te mantiene en camino.",
  "Lo que persigues también te está esperando; sigue caminando.",
  "Un día bien vivido es la mejor meta que puedes cumplir.",
  "Se puede ser amable y firme a la vez: ambas cosas te hacen fuerte.",
  "Cuando algo te importe de verdad, encontrarás el tiempo.",
  "Hoy encontrarás algo por lo que sonreír, solo tienes que buscarlo.",
  "Fíjate en las cosas buenas, aunque sean pequeñas: están ahí.",
  "Cuando lo hagas con ganas, el esfuerzo se transforma en alegría.",
  "Disfruta del camino: la meta no es lo único que importa.",
  "Hoy tienes algo que ayer no tenías: otra oportunidad.",
  "Un nuevo comienzo cabe en cualquier día, incluido este.",
  "Un día lleno de pequeñas victorias es un gran día.",
  "Cada día que lo intentas, estás más cerca de lograrlo.",
  "Hoy, haz algo que tu yo del futuro te agradezca.",
  "No hay atajos, pero cada paso cuenta el doble cuando lo das con ganas.",
  "Un poco cada día termina siendo muchísimo.",
  "Cuida de ti: es la base de todo lo que quieres lograr.",
  "Si hoy lo intentas, mañana tendrás una razón más para seguir.",
  "Mantén la cabeza fría, el corazón cálido y las manos ocupadas.",
  "No compares tu capítulo uno con el capítulo veinte de otra persona.",
  "La vida premia a quienes se atreven a empezar.",
  "Hazlo por ti, hazlo con ganas y hazlo hoy.",
  "Tus metas no son demasiado grandes; tus pasos solo tienen que ser constantes.",
  "Tu valor está en lo que eres, no en lo que produces.",
  "Pregunta, prueba, equivócate y mejora: así aprende cualquiera.",
  "Vive hoy de forma que tu yo de mañana quiera darte las gracias.",
  "Haz hoy lo que puedas, y mañana lo que puedas de nuevo; así se llega.",
  "Respeta tu proceso: cada uno florece a su tiempo.",
  "El éxito se construye con días normales hechos con constancia.",
  "Hay días de siembra y días de cosecha: hoy siembras, y está bien.",
  "Haz que hoy sea el día en que empezaste de verdad.",
  "Ayer ya pasó, mañana aún no llegó: hoy es tu momento.",
  "Tu esfuerzo hoy no se mide por lo grande, sino por lo constante.",
  "Dale una oportunidad a ese proyecto que te hace ilusión.",
  "Hoy tu única tarea es hacer lo que puedas con cariño.",
  "Mantén tus metas a la vista y tus pies en el presente.",
  "Tu mejor versión se construye con decisiones diarias, no con grandes saltos.",
  "Lo que piensas de ti marca lo que haces: piénsalo con cariño.",
  "La mejor inversión es la que haces en ti.",
  "Haz de cada día un ensayo de la vida que quieres.",
  "Que la calma te acompañe y la constancia te guíe.",
  "No es magia, es constancia; y tú tienes de sobra.",
  "Descansar también es avanzar: recarga y vuelve con fuerza.",
  "El camino se ilumina mientras caminas: da el primer paso.",
  "No te des por vencido: la recompensa suele esconderse tras la siguiente prueba.",
  "Que tus decisiones de hoy se parezcan a la vida que quieres.",
  "Un propósito claro hace ligero cualquier esfuerzo.",
  "Sueña en grande, empieza en pequeño, sigue sin parar.",
  "El esfuerzo callado también construye grandes cosas.",
  "Eres una persona valiosa, con ideas valiosas y un día por delante.",
  "Cree en tus planes, aunque aún sean pequeños.",
  "Haz de tu esfuerzo un hábito y de tu hábito, tu fuerza.",
  "Hoy es el día de dejar de pensarlo y empezarlo.",
  "Lo que sueñas merece que le dediques un rato cada día.",
  "Cada intento fallido te acerca al que sí funciona.",
  "Cada logro empezó con alguien que dijo: voy a intentarlo.",
  "Un tropiezo no borra todo lo que has avanzado.",
  "No esperes el momento perfecto: hazlo perfecto ahora con lo que tienes.",
  "La clave no es la fuerza, es la constancia.",
  "Las mejores decisiones se toman con calma y se cumplen con constancia.",
  "Cuanto más practicas, más fácil te resulta: sigue practicando.",
  "Tú puedes con esto; no es la primera vez que superas algo difícil.",
  "Dedica unos minutos hoy a aprender algo que te apasione.",
  "Quien se levanta con ganas, ya ha empezado a ganar.",
  "Tu día es una oportunidad; aprovéchala con una sonrisa.",
  "Una idea sola no cambia nada; una idea con acción lo cambia todo.",
  "Un gesto amable cuesta poco y puede cambiar el día de otra persona.",
  "No pares hasta que te sientas orgulloso de ti.",
  "Comienza con lo fácil y la motivación vendrá detrás.",
  "Tu ritmo es el correcto, aunque no se parezca al de los demás.",
  "Con paciencia y cariño todo florece.",
  "Tu actitud de hoy decide cómo se verá tu día.",
  "Tu historia aún se está escribiendo, y va por buen camino.",
  "Haz hueco para lo que te hace bien; el resto, ya cabrá.",
  "Dale a tu día una buena razón para ser especial.",
  "Hay mucho de bueno esperándote en el siguiente paso.",
  "La paciencia también es una forma de avanzar.",
  "Un paseo, un vaso de agua y una buena idea: ya es un buen comienzo.",
  "Rodéate de calma, de metas claras y de gente que te sume.",
  "Nunca es tarde para aprender algo nuevo ni para empezar de nuevo.",
  "Unos minutos de ilusión al día cambian cualquier rutina.",
  "Cree en ti: ya has hecho cosas que antes parecían imposibles.",
  "Pasito a pasito se recorren los caminos más largos.",
  "Tachar una tarea de la lista sabe a pequeña victoria: tacha una hoy.",
  "Tienes tiempo de sobra para lo que de verdad importa: elígelo.",
  "Si lo puedes imaginar, ya tienes la mitad del camino empezado.",
  "Organizarte es regalarte tiempo para lo que de verdad te gusta.",
  "Pase lo que pase, tú eliges cómo responder.",
  "Hoy es una nueva oportunidad para hacerlo un poco mejor que ayer.",
  "Valiente no es quien no tiene miedo, sino quien da el paso con él.",
  "Eres el autor de tu historia; hoy toca una buena página.",
  "Todo gran árbol fue una semilla que no se rindió.",
  "Hazlo fácil: divide, empieza y termina.",
  "Hoy no te pido que corras: te pido que no te detengas.",
  "Un día difícil no es un mal año: tú eres más grande que este momento.",
  "Lo que te propones con cariño, lo sostienes con facilidad.",
  "Que la prisa no te quite la alegría: avanza con calma.",
  "Todo lo que hoy haces con ganas se nota; sigue así.",
  "Haz algo que te dé un poquito de miedo; así se crece.",
  "Con orden en el día, la cabeza se despeja y el ánimo sube.",
  "Hay fuerza en ti que aún no has usado: hoy es un buen día para descubrirla.",
  "Cada vez que te levantas, ganas fuerza para la siguiente caída.",
  "Tu ilusión es la mejor brújula; síguela hoy.",
  "Respeta tus tiempos, celebra tus avances y sigue a tu ritmo.",
  "No tienes que ser perfecto para ser valioso.",
  "Si te caes, levántate; si te cansas, descansa; pero no te quedes ahí.",
  "Lo importante no es ir rápido, es no dejar de caminar.",
  "No necesitas más tiempo, necesitas empezar con el que tienes.",
  "La vida es mejor cuando haces lo que te gusta, aunque sea un ratito.",
  "Hoy brilla a tu manera: el mundo necesita tu versión.",
  "No hace falta ver toda la escalera; basta con subir el primer peldaño.",
  "Compartir tus metas con alguien las hace más fáciles de alcanzar.",
  "Gánale la partida a la pereza con solo cinco minutos de empezar.",
  "Tu futuro se construye con lo que haces hoy, no con lo que piensas hacer.",
  "Reserva hoy un ratito solo para ti: te lo has ganado.",
  "Eres el protagonista de tu día: dale una buena escena.",
  "Respira, ordena tus ideas y da el siguiente paso.",
  "Tienes tiempo, ganas y capacidad: solo falta empezar.",
  "Eres capaz de aprender cualquier cosa que te propongas con paciencia.",
  "Hazlo con calma, hazlo con ganas, hazlo a tu manera.",
  "Eres una obra en progreso, y va quedando preciosa.",
  "Si hoy te sientes pequeño, recuerda que las semillas también lo son.",
  "Empieza el día con tu mejor intención y verás cómo te acompaña.",
  "Hoy te mereces un día tranquilo, sin prisas y con buenas noticias.",
];
